# Generated by Django 5.2.5 on 2025-11-15 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="github_url",
            field=models.URLField(blank=True, help_text="GitHub repository URL"),
        ),
        migrations.AddField(
            model_name="project",
            name="project_url",
            field=models.URLField(blank=True, help_text="Live project URL"),
        ),
    ]
