# Generated by Django 5.2.5 on 2025-11-15 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_blogpost_contactmessage_education_experience_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="profile_image_url",
            field=models.URLField(
                blank=True,
                help_text="External image URL (e.g., from Google Photos, Imgur, etc.)",
            ),
        ),
    ]
