# Generated by Django 5.2.5 on 2025-11-15 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0004_profile_profile_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="api_documentation_url",
            field=models.URLField(
                blank=True, help_text="Swagger/OpenAPI documentation URL"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="design_decisions",
            field=models.TextField(
                blank=True, help_text="Key technical decisions and trade-offs"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="problem_statement",
            field=models.TextField(
                blank=True, help_text="The problem this project solves"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="solution_approach",
            field=models.TextField(
                blank=True, help_text="How the solution addresses the problem"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="technical_architecture",
            field=models.TextField(
                blank=True, help_text="System architecture and component interaction"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="testing_strategy",
            field=models.TextField(
                blank=True, help_text="Testing approach and coverage"
            ),
        ),
    ]
